### ISSUE TITLE
Be able to connect to an IP 

### ISSUE THREAD

**Issue by aholzel** [eclecticiq/intelligence-center-app-splunk-ta#20]
Please make the app able to connect to an IP address and not only to a host name. This means that also [Issue #19 ](https://github.com/eclecticiq/intelligence-center-app-splunk-ta/issues/19) needs to be resolved. This is especially useful in a test setup.

**Comment by himynamesdave** [comment]
Hey @aholzel --

I've taken a look at this, and not sure why we ever implemented such a validation.

We're planning a fix in the next release (ETA 2-3 weeks)

**Comment by himynamesdave** [comment]
fixed in 4bc369b
