### ISSUE TITLE
Allow cron scheduling for input

### ISSUE THREAD

**Issue by aholzel** [eclecticiq/intelligence-center-app-splunk-ta#21]
If you create a new input to collect observables you need to give a interval to do the collection. There is a validation done on this input and it only allows for integer input. However this is not a wanted situation. Splunk allows this field to also be a cron schedule. The cron schedule makes it possible to synchronise the time that the TIP creates the feed and the time that Splunk connects to the TIP to get the new packages. This way you know for sure that you have up-to-date info in Splunk. If you only allow for a interval you will never know when Splunk will connect to the TIP and get the info, so it may be that if gets the info from the TIP 1 minute before the TIP creates new packages.

**Comment by himynamesdave** [comment]
@aholzel this is a good request, and something that should exist.

We will add the option to select interval as cron time (in addition to set time interval, as is now) in the next release.

**Comment by himynamesdave** [comment]
fixed in a50aad4
