### ISSUE TITLE
Start date for "create a new input" page

### ISSUE THREAD

**Issue by kknaack-eiq** [eclecticiq/intelligence-center-app-splunk-ta#28]
On the page to create a new input you need to give a Start date.
+ why the yyyy-mm-ddThh:mm:ss.SSSSSS format ? are the SSSSSS really needed?
+ might be usefull to make notice that this date can not by more than 90 days in the past.
+ is it possible to make "-xx days" an option?

**Comment by himynamesdave** [comment]
In future please split each issue / feature request into a new ticket. I will do this now, but in future tickets with multiple request will be rejected.

**Comment by himynamesdave** [comment]
As above;

https://github.com/eclecticiq/intelligence-center-app-splunk-ta/issues/28#issuecomment-1326505693

Closing this issue in favour of individually created tickets for each issue.
